# Fetching and Loading Environmental Data

In this tutorial, we will use Kadlu to retrieve environmental data from online sources and load the data into numpy arrays for further processing.

The first step is to import kadlu. Note that the [datetime](https://docs.python.org/3/library/datetime.html) package is used to specify dates and times

In [1]:
from datetime import datetime
import kadlu

### Quick start guide

With Kadlu, environmental data can be downloaded and stored in one step. Here, we demonstrate how to obtain modeled surface salinity data from HYCOM for the geographic region $47^{\circ}$N to $49^{\circ}$N and $-63^{\circ}$W to $-61^{\circ}$W for the first week of January 2013.     

In [2]:
# fetch and load salinity (g/kg salt in water)
salinity, lat, lon, epoch, depth = kadlu.load(
        source='hycom', var='salinity',
        south=47, west=-63, 
        north=49, east=-61, 
        bottom=0, top=0,
        start=datetime(2013, 1, 1), end=datetime(2013, 1, 7))

HYCOM salinity  logged 60772 points in region	{"bottom": "5000", "east": "-62", "end": "2013-01-02 00:00:00", "north": "48", "south": "46", "start": "2013-01-01 00:00:00", "top": "0", "west": "-64"}
HYCOM salinity  logged 121544 points in region	{"bottom": "5000", "east": "-62", "end": "2013-01-03 00:00:00", "north": "48", "south": "46", "start": "2013-01-02 00:00:00", "top": "0", "west": "-64"}
HYCOM salinity  logged 121544 points in region	{"bottom": "5000", "east": "-62", "end": "2013-01-04 00:00:00", "north": "48", "south": "46", "start": "2013-01-03 00:00:00", "top": "0", "west": "-64"}
HYCOM salinity  logged 121544 points in region	{"bottom": "5000", "east": "-62", "end": "2013-01-05 00:00:00", "north": "48", "south": "46", "start": "2013-01-04 00:00:00", "top": "0", "west": "-64"}
HYCOM salinity  logged 121544 points in region	{"bottom": "5000", "east": "-62", "end": "2013-01-06 00:00:00", "north": "48", "south": "46", "start": "2013-01-05 00:00:00", "top": "0", "west": "-64"}
H

Note how the arguments `bottom` and `top` are both set to `0`, thereby selecting only data at a depth of 0 m, i.e., at the surface. 

The `load` function produced flattened numpy arrays, the length of which corresponds to the number of data points in the selected geographic region, depth range, and temporal window. 

In [3]:
# print the first 10 values of each array
print(lat[0:10])      # latitude (degrees north)
print(lon[0:10])      # longitude (degrees west)
print(depth[0:10])    # depth (meters)
print(epoch[0:10])    # time (hours since 00:00:00 on 1 January 2000)
print(salinity[0:10]) # ocean salt content (g/kg)

[47. 47. 47. 47. 47. 47. 47. 47. 47. 47.]
[-62.96002197 -62.88000488 -62.79998779 -62.7199707  -62.64001465
 -62.55999756 -62.47998047 -62.40002441 -62.32000732 -62.23999023]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[113991. 113991. 113991. 113991. 113991. 113991. 113991. 113991. 113991.
 113991.]
[30.791 30.886 30.92  30.903 30.874 30.853 30.817 30.747 30.714 30.636]


We can use the `epoch_2_dt` function to convert the time values into a more human-friendly date-time format, 

In [4]:
print(kadlu.epoch_2_dt(epoch[0]))

2013-01-01 15:00:00


### Data sources
Kadlu includes functionality to load data from a variety of different data sources. For a high level overview, print the source_map:

In [5]:
print(kadlu.source_map)


    CHS   (Canadian Hydrography Service)
          bathymetry:       bathymetric data in Canada's waterways. metres, variable resolution 

    ERA5  (Global environmental dataset from Copernicus Climate Data Store)
          wavedir:          mean wave direction, degrees
          waveheight:       combined height of wind, waves, and swell. metres
          waveperiod:       mean wave period, seconds
          wind_uv:          wind speed computed as sqrt(u^2 + v^2) / 2, where u, v are direction vectors
          wind_u:           wind speed coordinate U-vector, m/s
          wind_v:           wind speed coordinate V-vector, m/s
          precipitation:
          precip_type:
          snowfall:
          flux_ocean:
          flux_waves:
          stress_ocean: 

    GEBCO (General Bathymetric Chart of the Oceans)
          bathymetry:       global bathymetric and topographic data. metres below sea level 

    HYCOM (Hybrid Coordinate Ocean Model)
          salinity:         g/kg sal

for more information on a specific source, print the class:

In [6]:
print(kadlu.hycom())

Native hycom .[ab] data converted to NetCDF at the Naval
Research Laboratory, interpolated to 0.08° grid between
40°S-40°N (0.04° poleward) containing 40 z-levels.
Availability: 1994 to 2015
	https://www.hycom.org/data/glbv0pt08

function input arguments:
	(south, north, west, east, start, end, top, bottom)

class functions:
	load_hycom
	load_salinity
	load_temp
	load_water_u
	load_water_uv
	load_water_v



keyword arguments can be passed as a dictionary when using the same load arguments for multiple datatypes

In [7]:
kwargs = dict(
        south=47, west=-63, 
        north=49, east=-61, 
        bottom=0, top=0,
        start=datetime(2013, 1, 1), end=datetime(2013, 1, 7))

bathy1, lat1, lon1 = kadlu.load(source='gebco', var='bathymetry', **kwargs)

waveheight2, lat2, lon2, epoch2 = kadlu.load(source='era5', var='waveheight', **kwargs)

loading data from The GEBCO_2020 Grid - a continuous terrain model for oceans and land at 15 arc-second intervals
GEBCO bathymetry  logged 0 points in region	{"east": "-62", "north": "48", "south": "46", "west": "-64"}
loading data from The GEBCO_2020 Grid - a continuous terrain model for oceans and land at 15 arc-second intervals
GEBCO bathymetry  logged 0 points in region	{"east": "-62", "north": "50", "south": "48", "west": "-64"}
loading data from The GEBCO_2020 Grid - a continuous terrain model for oceans and land at 15 arc-second intervals
GEBCO bathymetry  logged 0 points in region	{"east": "-60", "north": "48", "south": "46", "west": "-62"}
loading data from The GEBCO_2020 Grid - a continuous terrain model for oceans and land at 15 arc-second intervals
GEBCO bathymetry  logged 0 points in region	{"east": "-60", "north": "50", "south": "48", "west": "-62"}
ERA5 significant_height_of_combined_wind_waves_and_swell  logged 529 points in region	{"east": "-62", "end": "2013-01-02 00:

### Manual loading from netcdf and geotiff 
Kadlu can load from netcdf- and geotiff-formatted data using the 'load_file' function:

In [9]:
kwargs = dict(south=47, west=-63, north=49, east=-61)

bathy3, lat3, lon3 = kadlu.load_file(filepath='/storage/GEBCO_2020.nc', **kwargs)

loading data from The GEBCO_2020 Grid - a continuous terrain model for oceans and land at 15 arc-second intervals


When loading from an arbitrary netcdf database, data transformation must be done by the user. For example, when loading GEBCO netcdf data directly from the file instead of the gebco().load_bathymetry function, bathymetric values will be returned as a measure of elevation (equal to depth * -1)

In [10]:
# returns a 2D array of elevation values
bathy3

array([ 56.,  56.,  56., ..., 116., 113., 115.])